hw added
MeowKT/first-term pull request #1
Opened 2020-07-01 13:41 UTC by MeowKT

2020-07-03 18:35 UTC, kt-cpp commented on asm/mul.asm
> +                clc
зочем?

2020-07-03 18:36 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rsi, [rbp - LEN]
А может в регистр все же сохранишь адрес `additional number`

2020-07-03 18:37 UTC, kt-cpp commented on asm/mul.asm
> +;   answer is written to r8
В контракте должно быть указано что `r8` должен указывать на участок памяти `2*rcx`

2020-07-03 18:39 UTC, kt-cpp commented on asm/mul.asm
> +;    sum is written to rsi
Про `reminder` ни слова ...

2020-07-03 18:39 UTC, kt-cpp requested changes
Исправь косяки и поправь табы еще

2020-07-03 21:06 UTC, MeowKT commented on asm/mul.asm
> +;    sum is written to rsi
fixed

2020-07-03 21:06 UTC, MeowKT commented on asm/mul.asm
> +;   answer is written to r8
fixed

2020-07-03 21:06 UTC, MeowKT commented on asm/mul.asm
> +                lea             rsi, [rbp - LEN]
fixed

2020-07-03 21:41 UTC, MeowKT commented on asm/mul.asm
> +                clc
clc не нужен 
ошибка

2020-07-05 18:56 UTC, kt-cpp approved these changes
Пойдет

2020-07-05 18:56 UTC, merged