vector added
MeowKT/first-term pull request #2
Opened 2020-07-02 16:26 UTC by MeowKT

2020-07-02 19:42 UTC, kt-cpp requested changes
миноры. код интересный

2020-07-02 19:42 UTC, kt-cpp commented on vector/vector.h
> +        T safe = x;
это копирование нужно не всегда

2020-07-02 19:42 UTC, kt-cpp commented on vector/vector.h
> +        size_t new_capacity = (capacity_ + 1) * 2;
лучше все таки степенью двойки, через тернарник удобно

2020-07-02 19:42 UTC, kt-cpp commented on vector/vector.h
> +        std::rotate(begin() + l, begin() + l + len, end());
just wow

2020-07-02 19:42 UTC, kt-cpp commented on vector/vector.h
> +    iterator erase(const_iterator first, const_iterator last)
добавь проверку, если интервал пуст, то ничего не делать

2020-07-02 19:42 UTC, kt-cpp commented on vector/vector.h
> +        data_ = capacity ? static_cast<T*>(operator new(capacity * sizeof(T))) : nullptr;
когда пишут структуры с кастомным аллокатором, то для удобства делают метод который аллокает сколько нужно. например static T * alloc_(size_t), и туда такую логику закладывают. но это просто инфа, мб тебе интересно, переделывать не надо.

2020-07-02 19:42 UTC, kt-cpp commented on vector/vector.h
> +#include <cstring>
cstring для кого?

2020-07-02 22:57 UTC, MeowKT commented on vector/vector.h
> +#include <cstring>
Думал memcpy нужен, не понадобился(забыл убрать)

2020-07-02 22:57 UTC, MeowKT commented on vector/vector.h
> +        std::rotate(begin() + l, begin() + l + len, end());
xd

2020-07-02 23:51 UTC, MeowKT commented on vector/vector.h
> +    iterator erase(const_iterator first, const_iterator last)
fixed

2020-07-02 23:54 UTC, MeowKT commented on vector/vector.h
> +        T safe = x;
fixed

2020-07-02 23:54 UTC, MeowKT commented on vector/vector.h
> +        size_t new_capacity = (capacity_ + 1) * 2;
fixed

2020-07-03 06:09 UTC, kt-cpp commented
в erase подразумевалось len > 0

2020-07-03 06:10 UTC, kt-cpp approved these changes

2020-07-03 06:10 UTC, merged